### PR TITLE
Fixes the schema generation bug

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* Uses `OptimizedSchemaUpdate` for all schema updates
 * Adds condition to `OptimizedSchemaUpdate` to only modify timeout table PK

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please review. I decided to go with no tests because I could not figure out a decent way to test it, other than running a bunch of integration-level scenarios, each after full DB clleanup and these would be too costly IMO.

**Comment by MarcinHoppe** [comment]
@SzymonPobiega: this PR targets `master`. Was this the original intent or was it `develop`?

**Comment by SzymonPobiega** [comment]
@MarcinHoppe I was not sure when I created it, if this should be a patch or not. What do you think?

**Comment by MarcinHoppe** [comment]
@SzymonPobiega I'd say develop + patch the version that customer has (6.2.7 IIRC).

**Comment by SzymonPobiega** [comment]
This solution won't work in case of non-default schema. In that case the SQL instructions contain also the schema name and `Replace` won't work. The alternative would be to use clever regular expressions.

**Comment by MarcinHoppe** [comment]
@SzymonPobiega This can be closed, it will be superseded by #270.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe OK. Let me know when you need a second pair of 👀

**Comment by MarcinHoppe** [comment]
7.1.4, 7.0.6, and 6.2.8 have been released to address this. Closing.

**Pull request closed without merging**
