### PR TITLE
Sagas should only be classes

### PR DESCRIPTION
**Pull request by SimonCropp**
pending https://github.com/Particular/NServiceBus/pull/4923

### CODE REVIEW

**Comment by timbussmann** [comment]
removing WIP as beta5 is on myget
ping @Particular/nhibernate-persistence-maintainers

**Comment by MarcinHoppe** [comment]
Build still red?

@timbussmann @SimonCropp Are you looking into this?

**Comment by SimonCropp** [comment]
@MarcinHoppe “no assemblies were found” seems unrelated to this pr

**Comment by SimonCropp** [comment]
And develop is also failing

**Comment by MarcinHoppe** [comment]
@SimonCropp Thanks. I am a little bit swamped atm but I'll request a review from myself not to let it slip.

**Comment by MarcinHoppe** [comment]
@SimonCropp @timbussmann I **think** I fixed the build steps that run ATTs. I will merge when the build is green.

**Pull request merged**
