### PR TITLE
Update tests to NServiceBus core 6.1.1

### PR DESCRIPTION
**Pull request by MarcinHoppe**

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
@Particular/nhibernate-persistence-maintainers I updated the acceptance tests to the latest core version.

**Comment by SzymonPobiega** [comment]
LGTM. Squash?

**Comment by MarcinHoppe** [comment]
Squad and merge, says the big green button.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe I hit the big green button ;-)

**Pull request merged**
