### PR TITLE
Adding missing sql transport endpoint configuration

### PR DESCRIPTION
**Pull request by HEskandari**

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
@HEskandari Is this PR something we need to merge to have SQL transport + NHibernate persistence ATTs up and running?

These tests should be running (see [this](https://github.com/Particular/NServiceBus/issues/4047#issuecomment-239740770) for background).

**Comment by HEskandari** [comment]
@MarcinHoppe Yes, on occasions I think I saw it fail random brittle tests which I never got around fixing , so I'd say for now lets rebase and see if it is still good.

**Comment by MarcinHoppe** [comment]
@Particular/nhibernate-persistence-maintainers This is green and good to go.

**Comment by HEskandari** [comment]
I'd say leave it for @SzymonPobiega to review, since both of us have worked on this PR!

**Comment by SzymonPobiega** [comment]
LGTM

**Pull request merged**
