### PR TITLE
Script generator usable in a test

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Adds `ScriptGenerator` class that can be used in tests to generate table creation scripts.

The `DDL.cs` test contains an example of how this would be used by users to generate their schemas as part of the build process.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers this seems to me a low hanging fruit that can drastically improve the deployment/scripting story. Please take a look, it's been a while since this has been done.

**Comment by mauroservienti** [comment]
NIce! does this mean that users can generate scripts during build and use them to deploy schema to environments?

**Comment by MarcinHoppe** [comment]
I think this would be best split into 2 parts: expose the necessary bits from the persister and add doco / sample how to incorporate it into your own project to generate the scripts. Thoughts?

**Comment by SzymonPobiega** [comment]
@mauroservienti yeah. @MarcinHoppe I agree it needs a sample but I would leave the `GenerateSciptsTest.cs` also here to make sure everything works as expected.

**Comment by SzymonPobiega** [comment]
I wonder if we would have to allow access to our build server to show it end-to-end...

**Pull request merged**
