### PR TITLE
Updated to new API in the core.

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Updates the persister to comply with https://github.com/Particular/NServiceBus/pull/3177. Does not build properly.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/engineers please review.

**Comment by timbussmann** [comment]
GH doesn't show all changes anyway

**Comment by SzymonPobiega** [comment]
@timbussmann yeah, updating acceptance tests is a pita:(

**Comment by timbussmann** [comment]
I think we should update ATT in a dedicated commit

**Comment by SzymonPobiega** [comment]
@timbussmann I did, but then I squashed :( Let me try to fix it.

**Comment by SzymonPobiega** [comment]
@timbussmann try now.

**Comment by timbussmann** [comment]
thanks, much better! Looks good to me :+1:

**Comment by DavidBoike** [comment]
:+1: to merge

**Pull request merged**
