### PR TITLE
NHibernate persistence and SQL transport do not work well together without TransactionScope

### PR DESCRIPTION
**Pull request by particularbot**
### Symptoms

When looking for a saga instance an exception is thrown:
```
System.InvalidOperationException: SqlConnection does not support parallel transactions.
```

### Who's affected

Users who use both SQLServer transport and NHibernate peristence but with disabled usage of `TransactionScope`:

```
configuration.Transactions().Enable();
configuration.Transactions().DisableDistributedTransactions();
```

### Workaround

Do not disable usage of `TransactionScope`

### Possible solution

As described [here](https://github.com/Particular/NServiceBus.NHibernate/issues/38#issuecomment-65210350) the solution might be to implement a custom `ITransactionFactory`. Alternatively we need to throw a more descriptive exception.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Added a better exception

**Comment by SzymonPobiega** [comment]
@johnsimons can you review?

**Comment by johnsimons** [comment]
@SzymonPobiega do you need help finishing this one off ?

**Comment by SzymonPobiega** [comment]
@johnsimons I've added a startup-time check using a feature that depends on both SQL transport and the shared storage. Do you think it makes sense?

**Comment by SzymonPobiega** [comment]
@johnsimons hold on with merging this for a moment

**Comment by SzymonPobiega** [comment]
Sorry for that. I wanted to do a small spike to absolutely sore we can't do this and now I am absolutely sure. More details in #38

**Comment by johnsimons** [comment]
@SzymonPobiega before merging, can you address https://github.com/Particular/NServiceBus.NHibernate/commit/3f6f09832d48699198f5d87c53450b165e9b9ce4#comments

**Comment by SzymonPobiega** [comment]
Hmmm.. I adressed it already... strange. Also 278 changed files seems wrong. Will push -f

**Comment by SzymonPobiega** [comment]
Files are OK, these are acceptance tests that I upgraded. The exception text is OK as per last commit ('The transaction WILL NOT be escalated bla bla ble')

**Comment by johnsimons** [comment]
:+1: to merge

**Pull request merged**
