### PR TITLE
Updating NHibernate repo to NSB Beta7

### PR DESCRIPTION
**Pull request by WojcikMike**
cc: @Particular/nhibernate-persistence-maintainers please merge

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@WojcikMike is there anything else other than AT upgrade? I mean, I can't review it on github.

**Comment by SzymonPobiega** [comment]
There is one failure in the ATs on the build server. I'll re-run them again.

**Comment by WojcikMike** [comment]
Update nuspec to:
<dependency id="NServiceBus" version="[6.0.0-beta0007, 7.0.0)" />

And update to use latest NSB. + update ATT 

I had to divide 1 test into 2:
When_registering_publishers_unobtrusive_messages had 2 test cases and it messed up routing. @timbussmann suggested to manually change it for now in NHibernate and we will fix it in the next release of core.

**Comment by WojcikMike** [comment]
Test have passed @SzymonPobiega

**Pull request merged**
