### PR TITLE
[WIP] Upgraded to RC

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* [x] Upgrade depedency on Core
 * [x] Re-add ATs using MSMQ
 * [x] Figure out why the ATs are failing randomly

TODO:
 * [ ] Move AT changes to core

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers something is off here. I failed to figure out what but the new message driven pub/sub tests I've added recently to the core are failing when running whole test suite. They tend to pass when run one-by-one and/or after cleaning the subscriber table...

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please hit the green button.

**Comment by HEskandari** [comment]
@SzymonPobiega not sure if you're finished with the branch. What's the pending todo?

**Comment by SzymonPobiega** [comment]
@HEskandari thanks!

**Pull request merged**
