### PR TITLE
Prepare infrastructure for RC1

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please hit the green button.

**Comment by danielmarbach** [comment]
Looks good

**Comment by danielmarbach** [comment]
If you allow I can merge

**Comment by SzymonPobiega** [comment]
Please, be my guest @danielmarbach !

**Comment by SzymonPobiega** [comment]
:tada:

**Pull request merged**
