### PR TITLE
Use optimized schema update to ensure correct indexes are created

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
I squashed it to be ready to cherry pick to the hotfix branch.

**Comment by SzymonPobiega** [comment]
Also, I narrowed down the affected specification in #280 to cases where the sagas share a base class. In case they don't share base class (e.g. implement `IContainSagaDataDirectly`) there is no problem.

**Comment by SzymonPobiega** [comment]
Replaced by #283

**Comment by tmasternak** [comment]
Should we delete the branch?

**Pull request closed without merging**
