### PR TITLE
Fixing Outbox and Timeout Persisters

### PR DESCRIPTION
**Pull request by HEskandari**
Remove dependency to the internalized Json serializer and updated to the latest core

### CODE REVIEW

**Comment by ramonsmits** [comment]
I'm taking those first few commits as granted or should those be reviewed?

Is there a corresponding issue for this change? I don't see an issue and also don't see in the comments why we moved to the json.net serializer.

**Comment by SimonCropp** [comment]
@HEskandari is there any particular thing u want reviewed since as it stand this PR has a very bad signal to noise ratio

**Comment by HEskandari** [comment]
@SimonCropp This commit 1c3561a. The rest is just upgrading to the latest NSB core.

**Comment by SzymonPobiega** [comment]
Hmmm didn't we decide to go with the `DataContralSerializer` by default?

**Comment by indualagarsamy** [comment]
@SzymonPobiega is that decision, i.e. to use DataContractSerializer documented in any issue?

**Comment by HEskandari** [comment]
@SzymonPobiega we did...I was actually a proponent of that! had an issue with ``DataContractSerializer`` as it is more than IDictionary<string, string> we are serializing here. Today, in the light of a fresh day, I managed to get the ``DataContractSerializer`` working, so I'll close this PR and send another clean one.

**Comment by SzymonPobiega** [comment]
@HEskandari :-)
@indualagarsamy I don't think it is. It was a slack conversation and few comments in various PRs. But I think in the long run it should go to some architectural vision of NSB.

**Comment by HEskandari** [comment]
It was discussed on this PR. https://github.com/Particular/NServiceBus.SqlServer/pull/152

**Comment by HEskandari** [comment]
Can close this one off now. The cleaner PR can be found [here][1].

[1]: https://github.com/Particular/NServiceBus.NHibernate/pull/157

**Pull request closed without merging**
