### PR TITLE
Upgrade to 7 of core

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@SzymonPobiega my attempt at fixing the build errors https://github.com/Particular/NServiceBus.NHibernate/pull/301

**Comment by SzymonPobiega** [comment]
@SimonCropp thanks ❤️

**Comment by SzymonPobiega** [comment]
Build is now green. @Particular/nhibernate-persistence-maintainers please review.

**Comment by MarcinHoppe** [comment]
Why did we do it before making a decision in https://github.com/Particular/PlatformDevelopment/issues/1197?

**Comment by SzymonPobiega** [comment]
I started doing it before it was put on hold and just wanted to get if done and out of my way. Still #1197 may conclude to not release it (which is a different thing than just upgrading the code). If we decide to have NH for V7, then the core will be in `develop`. If not then we'll have to tell customers what to do via doco.

**Pull request merged**
