### PR TITLE
Fixed mapping when saga data inherits from more than one abstract class

### LINKED ISSUE #114: .NET Framework 4.6 runtime: SagaData with abstract base class
After installing Visual Studio 2015, which includes the .NET Framework 4.6 runtime, I am receiving an error on startup when using SagaData with an abstract base class:

"NHibernate.MappingException: Could not compile the mapping document: mapping_by_code ---> NHibernate.MappingException: Cannot extend unmapped class"

Please have a look here for a minimal example:
https://github.com/sveinfid/NHibernateNETFramework46Bug

Note that the project is still targeting .NET 4.5.2. The project does not have to be upgraded to 4.6 for this to become an issue.

This may be related this issue which is about the ordering of the results returned by Assembly.GetTypes(), which has changed between .NET 4.5.2 and 4.6: http://stackoverflow.com/questions/31321275/nhibernate-mapping-by-code-in-net-4-6-throws-cannot-extend-unmapped-class#comment51373729_31321275

Full stack trace:
2015-07-31 11:36:12.566 ERROR NServiceBus.GenericHost Exception when starting en
dpoint.
NHibernate.MappingException: Could not compile the mapping document: mapping_by_
code ---> NHibernate.MappingException: Cannot extend unmapped class: NHibernateN
ETFramework46Bug.MySagaDataSuperClass, NHibernateNETFramework46Bug, Version=1.0.
0.0, Culture=neutral, PublicKeyToken=null
   at NHibernate.Cfg.XmlHbmBinding.ClassBinder.GetSuperclass(String extendsName)

   at NHibernate.Cfg.XmlHbmBinding.MappingRootBinder.AddEntitiesMappings(HbmMapp
ing mappingSchema, IDictionary`2 inheritedMetas)
   at NHibernate.Cfg.XmlHbmBinding.MappingRootBinder.Bind(HbmMapping mappingSche
ma)
   at NHibernate.Cfg.Configuration.AddDeserializedMapping(HbmMapping mappingDocu
ment, String documentFileName)
   --- End of inner exception stack trace ---
   at NHibernate.Cfg.Configuration.LogAndThrow(Exception exception)
   at NHibernate.Cfg.Configuration.AddDeserializedMapping(HbmMapping mappingDocu
ment, String documentFileName)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NServiceBus.Features.NHibernateStorageSession.Setup(FeatureConfigurationCo
ntext context) in c:\BuildAgent\work\5135de308b2f3016\src\NServiceBus.NHibernate
\SharedSession\NHibernateStorageSession.cs:line 31
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState feature
State, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in
 c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActiva
tor.cs:line 240
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationCo
ntext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Featu
res\FeatureActivator.cs:line 116
   at NServiceBus.Configure.Initialize() in c:\BuildAgent\work\3206e2123f54fce4\
src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\BuildAgent\wo
rk\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 19
   at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) i
n c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHos
t.cs:line 119
   at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src
\NServiceBus.Hosting.Windows\GenericHost.cs:line 58

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* Also fixed acceptance tests.

Fixes #114

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please review. It seems like `union-subclass` mapping always generates table-per-concrete class so skipping intermediate abstract classes in the mapping does not affect the end result but I am not 100% sure.

**Comment by HEskandari** [comment]
I reviewed. Didn't see any problems. What's your concern @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@HEskandari my biggest concern was excluding these abstract classes in the middle of the hierarchy. Based on NH doco it should work fine. It is also confirmed by our tests. But the actual mapping document looks differently.

**Comment by HEskandari** [comment]
@SzymonPobiega So I'm hearing 'we don't have sufficient test coverage'? :) Would different mapping document generated by NH be a deal breaker?

**Comment by SzymonPobiega** [comment]
@HEskandari you are right. I've added a test that makes sure all properties inherited from abstract bases classes are included in the mapping.

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please merge if you think test coverage is good enough.

**Pull request merged**
