### PR TITLE
Removed the code that was responsible for sharing the connection instance

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Removed the core responsible for sharing an instance of `SqlConnection`. Based on the changes done in https://github.com/Particular/NServiceBus.SqlServer/pull/252 the same goal will be achieved by having separate instances of `SqlConnection` in transport and in persistence provided that both use the same connection string. 

The key feature is early closing of transport connection that prevents DTC escalation when persistence connection is created.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers can you review? I'll rebased in the meantime. The corresponding change in the SQL transport has already been merged.

**Comment by SzymonPobiega** [comment]
This is now green on the build server (including ATs)

**Comment by HEskandari** [comment]
Is this a change in behavior in v7? Should we mention it in the upgrade docs? The code LGTM. I'm merging it since the build is now green.

**Comment by SzymonPobiega** [comment]
@HEskandari Maybe add something like this https://github.com/Particular/docs.particular.net/pull/1594 to the NH upgrade guide? Because we never know if people approach it from NH or SQL perspective.

**Comment by SzymonPobiega** [comment]
Scratch that. On the NH side the behavior is the same as in V6: if in ambient transaction mode and using same connection string as SQL transport, no DTC escalation.

**Comment by HEskandari** [comment]
@SzymonPobiega  :+1:

**Comment by HEskandari** [comment]
With this merged, think we can close #198 and do another release?

**Pull request merged**
