### PR TITLE
Changed ATTs infrastructure to newest ConfigureEndpointTestExecution

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to https://github.com/Particular/NServiceBus/pull/3514#issuecomment-189050351

### CODE REVIEW

**Comment by DavidBoike** [comment]
The Raven version of this PR got done as renames, but this has double the files changed because it went in as deletes and adds.

@SzymonPobiega how would you like to handle this?

cc @Particular/persistence-maintainers

**Comment by SzymonPobiega** [comment]
@DavidBoike I'll merge it and then review. We can always revert the commit if @danielmarbach wanted to flood us with changes to ATTs in order to sneak in one nasty bug ;-)

**Comment by SzymonPobiega** [comment]
@danielmarbach something is off. There are some problems with Oracle tests (this is expected, there are always problems with oracle tests) but there is something odd when that happens. I have this thing:

```
MSMQ receive operation failed System.Messaging.MessageQueueException (0x80004005): Queue handle can no longer be used to receive messages because the queue was deleted. The handle should be closed.
   at System.Messaging.MessageEnumerator.MoveNext(TimeSpan timeout)
   at NServiceBus.MessagePump.<InnerProcessMessages>d__6.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 128
```
repeated in the output multiple times. Seems like a race condition between the cleanup and shutdown?

**Comment by danielmarbach** [comment]
@SzymonPobiega Did you do the core upgrade? Is this still an issue?

**Comment by SzymonPobiega** [comment]
@danielmarbach not yet. I'll do it now.

**Comment by SzymonPobiega** [comment]
Core update PR here https://github.com/Particular/NServiceBus.NHibernate/pull/171

**Pull request merged**
