### PR TITLE
Hotfix 8.0.0-rc2

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by ramonsmits** [comment]
Closing as it is conflicting with #330 and will be reopened after that has been merged.

**Comment by ramonsmits** [comment]
Reopening as #330 has been merged.

**Comment by bording** [comment]
#337 will need to be merged first to fix the build error.

**Comment by bording** [comment]
Since this is a hotfix branch being merged in, we can't easily fix the inspection error here. I'll merge this and open a followup PR.

**Comment by bording** [comment]
I was largely reviewing from the standpoint of the release/branching process on this one. @ramonsmits will be the one to ask about implementation questions.

**Pull request merged**
