### PR TITLE
Fix subscriber version bug

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Adds a test to ensure the fix in the core works and versions are indeed ignores both when looking for subscriptions as well as when unsubscribing.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers please review the last commit. Previous ones were related to fixing acceptance tests after core upgrade.

**Comment by MarcinHoppe** [comment]
@SzymonPobiega This looks in line with what we discussed.

Build seems red, though 😢.

**Comment by SzymonPobiega** [comment]
Give that this test is a bit flaky and I did not touch it, I'd say it is OK to merge...

**Comment by MarcinHoppe** [comment]
@SzymonPobiega This looks like a race condition. I filed an issue in the Core repo to address this: Particular/NServiceBus#178.

I ran the build again. If it still pops up, I'll mark it as passed and merge.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe it's green! it's green! 🎉

**Comment by MarcinHoppe** [comment]
@SzymonPobiega :dancer:

**Pull request merged**
