### PR TITLE
[WIP] Update to core 6.1.0

### PR DESCRIPTION
**Pull request by andreasohlund**
WIP until the stable 6.1 is out Particular/NServiceBus#4377

### CODE REVIEW

**Comment by andreasohlund** [comment]
>The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

😱

**Comment by timbussmann** [comment]
@Particular/nhibernate-persistence-maintainers 6.1 is now officially released. Feel free to pick up this PR and update it to the final 6.1 package. It's up to you whether you decide to only update the test projects or if you update the main projects build dependency to 6.1 too. In case of the second option, please be careful to update nuspec dependencies only if you make use of newly available 6.1 APIs.

(the final release also contains shorter file paths which should solve problems with the test files)

**Comment by MarcinHoppe** [comment]
@andreasohlund Do we need to drop this PR in favor of a new one with updated acceptance test source packages?

**Comment by andreasohlund** [comment]
Either that or updating this one, let me know if you need a hand?

**Comment by MarcinHoppe** [comment]
Closing in favor of #249.

**Pull request closed without merging**
