### PR TITLE
Fixed handling of transactions in Add and TryRemove methods.

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Now these methods should properly recognize the transport transaction (be it TransactionScope or a TS+SqlConnection) and hook into it in order to provide exactly-once experience.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@weralabaj @HEskandari please review.

**Comment by ramonsmits** [comment]
There is missing context here. Why is this needed? Where is the issue?

**Comment by SzymonPobiega** [comment]
@ramonsmits as in description, the current code ignores the transport transaction and/or SQL connection which results in at-least-once behavior where we expect exactly-once (DTC MSMQ or SQL).

**Comment by weralabaj** [comment]
@SzymonPobiega FYI I updated the package to this PR, but that doesn't seem to solve the timeout issue. I'll need more time to investigate and would be good to get the latest core, so I'll look into that on Monday.

**Comment by SzymonPobiega** [comment]
Closing this one and creating another one based on develop.

**Comment by SzymonPobiega** [comment]
Replaced by #160

**Pull request closed without merging**
