### PR TITLE
Aligning OutboxRecord with TransportOperations to save allocations

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to https://github.com/Particular/NServiceBus/pull/3903

Can be merged when core changes are merged

### CODE REVIEW

**Comment by danielmarbach** [comment]
@MarcinHoppe since you are on a spree. Could you rebase this on top of your changes in #206 ?

**Comment by MarcinHoppe** [comment]
Will do.

**Comment by MarcinHoppe** [comment]
@danielmarbach Rebased.

@Particular/nhibernate-persistence-maintainers This seems to be a minor change so I will take it out of WIP.

**Comment by DavidBoike** [comment]
:+1:

**Comment by danielmarbach** [comment]
What's up with this one?

**Comment by SzymonPobiega** [comment]
@danielmarbach I am not convinced that in context of a NHibernate database call changing LINQ to for loops makes sense from performance point of view. Although I do understand we want to be as fast as possible in the core because core works all in-mem, here we have a cross-machine call (probably not only one). I prefer simplicity of LINQ (unless there is a way to prove the change gives us measurable benefit in terms of allocations.

**Pull request closed without merging**
