### PR TITLE
Update refs

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/nhibernate-persistence-maintainers  review please

**Comment by SzymonPobiega** [comment]
@SimonCropp have you checked if it builds in `Release`? Last time I tried GitVersion 3.4.1 it failed to generate the release number. I've created the PR but did not check if they released the patch yet. It might also happened that the tree is now different and it will generate the version correctly.

**Comment by SimonCropp** [comment]
@SzymonPobiega righ you are. blocked by https://github.com/GitTools/GitVersion/pull/827

**Comment by SimonCropp** [comment]
marked as WIP until unblocked

**Comment by DavidBoike** [comment]
There's a 3.5.2 of GitVersion on NuGet now. Does that unblock this?

**Comment by SzymonPobiega** [comment]
Yeah, the fix is included in 3.5.2 https://github.com/GitTools/GitVersion/commit/1134adebc6ddb577ff05e02efbcef99dcc7e4287. I'll take it forward.

**Comment by SzymonPobiega** [comment]
@SimonCropp @DavidBoike please merge is OK.

**Pull request merged**
