### PR TITLE
Allows to customize the outbox record mapping

### LINKED ISSUE #231: No way to influence mapping for OutboxRecord & TimeoutEntity
At my current client the DBA's have certain convensions that need to be followed with regards to object names in the database.

It doesn't look like it is possible to change any mappings for the internal classes used.
I can identify the code doing the mapping in the codebase, but i see no way of overriding the behavior without branching the code.

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Introduces the following API:

```
var p = b.UsePersistence<NHibernatePersistence>();
p.UseOutboxRecord<MyOutboxRecord,MyOutboxRecordMapping>();
```

Fixes #231 
### Plan of attack
- [x] Implement new API
- [x] [Doco pull](https://github.com/Particular/docs.particular.net/pull/2118)

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please review.

**Comment by HEskandari** [comment]
@SzymonPobiega think it can be reviewed now ;)

**Comment by MarcinHoppe** [comment]
I think updating the doco is missing from the PoA here.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe PoA updated. I'll work on doco now.

**Comment by SzymonPobiega** [comment]
OK, I've added a WIP doco pull. This is now ready for review @MarcinHoppe @HEskandari

**Comment by MarcinHoppe** [comment]
@SzymonPobiega Can we somehow enforce the constraints we documented about `MessageId`, `Dispatched`, and `DispatchedAt` columns?

**Comment by HEskandari** [comment]
This LGTM. I'll review the doco separately.

**Comment by SimonCropp** [comment]
anything else holding this up?

**Comment by SzymonPobiega** [comment]
@SimonCropp we have huge problems with flaky tests with NH. @MarcinHoppe are you OK with merging this one without the ATT passing?

**Comment by MarcinHoppe** [comment]
👍 from me to merge as long as only "known suspects" are red 😁.

**Pull request merged**
